#!/usr/bin/env bash
#Bash script that will display information about subdomains.

get_sub() {
	local domain="$1"
	local subdomain="$2"
	dig "${subdomain}.${domain}" +short | grep -v '^$' | awk -v subd="$subdomain" '{print "The subdomain "subd" is a A record and points to" $0}'
	}
if [ -n "$2" ]; then
	get_sub "$1" "$2"
else
for subdomain in www lb-01 web-01 web-02; do
	get_sub "$1" "$subdomain"
done
fi
