#!/usr/bin/env bash
#Create a certificate using certbot
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend https
    bind *:443 ssl crt /etc/haproxy/haproxy.cfg
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web1 192.168.1.100:80 check
    server web2 192.168.1.101:80 check
