#!/usr/bin/env bash
#Install nginx on your web-01
apt-get update
apt-get install -y nginx

echo "server {
	listen 80;
	location / {
		return 200 'Hello World!';
		}
}" > /etc/nginx/sites-available/default

killall nginx
nginx
