#!/usr/bin/env bash
#Bash script with the minimum number of commands to automate your fix.
rm /etc/nginx/sites-enabled/default
#listen on port 80
ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx restart
