#!/usr/bin/env bash
#Bash script with the minimum number of commands to automate your fix.
if ! command -v nginx; then
apt-get update
apt-get install -y nginx
service nginx start
fi
if ! sudo netstat -tl | grep 'nginx' > /dev/null; then
sudo sed -i 's/list [^;]*;/listen 80;/g' /etc/nginx/nginx.conf
sudo service nginx restart
fi
