#!/usr/bin/env bash
#Write a Bash script that creates the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2

    # Check for signals
    if [ -n "$(kill -l $1)" ]; then
        case $1 in
            TERM)
                echo "I hate the kill command"
                ;;
            INT)
                echo "Y U no love me?!"
                ;;
            QUIT|TERM)
                echo "Deleting PID file and terminating"
                rm /var/run/myscript.pid
                exit 0
                ;;
            *)
                echo "Unknown signal: $1"
                ;;
        esac
    fi
done
