#!/usr/bin/env bash
#Write a Bash script that stops 4-to_infinity_and_beyond process
pkill -f 4-to_infinity_and_beyond
while ps -ef | grep -v grep | grep 4-to_infinity_and_beyond > /dev/null; do
sleep 1
done
echo "Terminated"
