#!/usr/bin/env bash
#Write a Bash script that stops 4-to_infinity_and_beyond process
pid=$(pgrep -f "7-highlander")
kill -TERM  $pid
if [ -n "$(pgrep 67-stop_me_if_you_can)" ]; then
	echo "I am invincible!!!"
fi
