#!/usr/bin/env bash
#Bash script that displays Best School 10 times You must use the while loop You must use the if statement
i=0
while [ $i -lt 10 ]
do
        if [ $i == 9 ]; then
                echo Hi
        fi
        echo Best School
        i=$((i + 1))
done
