#!/usr/bin/env bash
#write a Bash script that accepts one argument
if [ $# -ne 1 ]; then
echo " ERROR"
exit 1
fi
user=$1
if ! id -u "$1" > /dev/null; then
	echo "'$1' not found"
	exit 1
fi
sudo -u "$user" "whoami"
