#!/usr/bin/env bash
#nginx must be running as nginx user
sudo chown -R nginx:nginx /etc/nginx /var/log/nginx /var/www/html
sudo tee /etc/nginx/sites-available/default << EOF
server { 
listen 8080;
}
EOF
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled
sed -i 's/#user nginx;/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx /usr/sbin/nginx
