#!/usr/bin/env bash
#nginx must be running as nginx user
sudo service nginx stop
sudo chown -R nginx:nginx /etc/nginx /var/log/nginx /var/lib/nginx
echo "server {listen 8080;}" > /etc/nginx/nginx.conf
sudo service nginx start
