#!/usr/bin/env bash
#nginx must be running as nginx user
sudo service nginx stop
sudo chown -R nginx:nginx /var/log/nginx /var/lib/nginx
sed -i 's/user\*snginx;/user nginx nginx;/g' /etc/nginx/nginx.conf
sudo service nginx start
